version: '3'

services:
  db:
    image: postgres
  migration:
    image: app
    build: . 
    command: python3 manage.py migrate
    links:
      - db
    depends_on:
      - db
  web:
    image: app
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app

    ports:
      - "8000:8000"
    depends_on:
      - db